- hosts: all

  vars:
    container_state: present
    
  roles: 
    - role : jaeger
      tags: podman
    - role : postgres
      tags: podman
    - role : pgadmin
      tags: pgadmin
    - role : kafka
      tags: pgadmin  