apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-todo-config
  labels:
    app: quarkus-todo
data:
  quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/hibernate_db
  quarkus.swagger-ui.always-include: "true"
  quarkus.ssl.native: "false"
  quarkus.jaeger.service-name: todo-app
  quarkus.jaeger.sampler-type: const
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.endpoint: http://jaegertracing:14268/api/traces
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-todo
  template:
    metadata:
      labels:
        app: quarkus-todo
    spec:
      containers:
        - name: quarkus-todo-app
          image: REGISTRY_IP:5000/quarkus/QUARKUS_BUILD/todo-app:VERSION
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: quarkus-todo-config
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-todo
  labels:
    app: quarkus-todo
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: quarkus-todo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus-todo
spec:
  rules:
    - host: quarkus-todo.jarry.dk
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: quarkus-todo
                port:
                  number: 8080
