apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-todo-config
  labels:
    app: quarkus-todo
data:
  quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/hibernate_db
  quarkus.swagger-ui.always-include: 'true'
  quarkus.jaeger.service-name: todo-app
  quarkus.jaeger.agent-host-port: 'jaegertracing:6831'
  quarkus.jaeger.endpoint: 'http://jaegertracing:14268/api/traces'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-todo
  template:
    metadata:
      labels:
        app: quarkus-todo
    spec:      
      containers:
        - name: quarkus-todo-app
          image: 192.168.1.36:5000/quarkus/todo-app:steep0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: quarkus-todo-config
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-todo
  labels:
    app: quarkus-todo
spec:
  type: NodePort
  ports:
   - port: 8080
  selector:
   app: quarkus-todo