# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven - todo-app-steep1
      run: mvn -B package --file todo-app-steep1/pom.xml
    - name: Build with Maven - todo-app-steep2
      run: mvn -B package --file todo-app-steep2/pom.xml
    - name: Build with Maven - todo-app-steep2-h2
      run: mvn -B package --file todo-app-steep2-h2/pom.xml
    - name: Build with Maven - todo-app-steep2-panache
      run: mvn -B package --file todo-app-steep2-panache/pom.xml      
    - name: Build with Maven - todo-app-steep3
      run: mvn -B package --file todo-app-steep3/pom.xml
    - name: Build with Maven - todo-app-steep4
      run: mvn -B package --file todo-app-steep4/pom.xml
    - name: Build with Maven - todo-app-steep5
      run: mvn -B package --file todo-app-steep5/pom.xml
    - name: Build with Maven - todo-app-steep6
      run: mvn -B package --file todo-app-steep6/pom.xml
